# Generated by Django 3.1.1 on 2020-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.FloatField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('image', models.ImageField(default='default.jpg', upload_to='product/agriculture')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
