# Generated by Django 3.1.1 on 2020-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name': 'Detail', 'verbose_name_plural': 'Detail'},
        ),
        migrations.AddField(
            model_name='productdetails',
            name='description',
            field=models.CharField(default='s', max_length=300),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='protectFeature',
            field=models.CharField(default='s', max_length=100),
        ),
    ]
